# Generated by Django 4.1.4 on 2022-12-26 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_studentdatainfo_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('absent', models.BooleanField(default=False)),
                ('matricNumber', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.studentdatainfo')),
            ],
        ),
    ]
